steps:
  # Build the Docker image for the frontend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/healthcare-testgen-frontend:${COMMIT_SHA}'
      - '-f'
      - 'frontend/Dockerfile'
      - '.'
    dir: 'frontend'

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/healthcare-testgen-frontend:${COMMIT_SHA}'

  # Deploy the frontend service to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'healthcare-testgen-frontend'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/healthcare-testgen-frontend:${COMMIT_SHA}'
      - '--region'
      - 'europe-west1' # Or your preferred region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # Adjust based on your authentication needs
      - '--port'
      - '80' # Nginx serves on port 80
    # The 'dir' parameter is not needed here as gcloud run deploy operates on the image
    # and the current working directory for Cloud Build is the root of the repository.
images:
  - 'gcr.io/${PROJECT_ID}/healthcare-testgen-frontend:${COMMIT_SHA}'
