steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/sm-testcase-generator:$COMMIT_SHA",
        "--build-arg", "VITE_FIREBASE_API_KEY=${_FIREBASE_API_KEY}",
        "--build-arg", "VITE_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}",
        "--build-arg", "VITE_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}",
        "--build-arg", "VITE_FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}",
        "--build-arg", "VITE_FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID}",
        "--build-arg", "VITE_FIREBASE_APP_ID=${_FIREBASE_APP_ID}",
        "--build-arg", "VITE_API_BASE_URL=${_BACKEND_SERVICE_URL}/api",
        "--build-arg", "VITE_WEBSOCKET_URL=${_BACKEND_SERVICE_URL}",
        "./frontend/",
      ]
  
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-west1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/sm-testcase-generator:$COMMIT_SHA",
      ]
  
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "europe-west1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/sm-testcase-generator:$COMMIT_SHA",
        "--region",
        "europe-west1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--port",
        "8080"
      ]

options:
  logging: CLOUD_LOGGING_ONLY